app/views/dashboard.py
from mongo_service import MongoService
from flask import Blueprint, render_template, make_response


dashboard = Blueprint('dashboard', __name__)

@dashboard.route('/')
@dashboard.route('/home')
def home():
    """
    Render the home page for the 'dashboard' module
    This returns the names and URLs of adjacent directories
    """
    return render_template("homescreen.html", tagname = 'home')





@dashboard.route('/policylist')
def policylist():
    """
    List of objects
    """
    mongo_service = MongoService()
    policies = mongo_service.find_policies(None)
    policies_ids = {polici["id"]: {"description": polici["description"], "device_actor": polici["device_actor"], "device_actee": polici["device_actee"]}for polici in policies}
    return render_template('policylist.html', tagname = 'policylist', policies_ids = policies_ids)

@dashboard.route('/pendingPolicies')
def pendingPolicies():

    return render_template('pendingPolicies.html')

@dashboard.route('/community')
def community():

  return render_template('community.html')


@dashboard.route('/addPolicy')
def addPolicy():
    return render_template('addPolicy.html', tagname='addPolicy')

@dashboard.route('/deletePolicy')
def deletePolicy():
    mongo_service= MongoService()
    policies = mongo_service.find_policies(None)
    policyid = [policy["id"] for policy in policies]
    return render_template('deletePolicy.html', tagname='deletePolicy', policyid=policyid)

@dashboard.route('/changePolicy')
def changePolicy():
    return render_template('changePolicy.html', tagname='changePolicy')


@dashboard.route('/notifications')
def notifications():

        return render_template('notifications.html', tagname= 'notifications')



@dashboard.route('/command')
def command():
    """
    Render the command page for the 'dashboard' module
    """
    return render_template('command.html', tagname = 'command')

app/views/policy_api.py
from cProfile import label
import json
from logging import Logger, error
from operator import ne
from flask import Blueprint, config, request, url_for, redirect, Response, make_response, jsonify, session, render_template
from flask import current_app as app
from flask_login import current_user as user
from mongo_service import MongoService
from utils import is_json_request, format_thing_description, transform_links

policy_api = Blueprint('policy_api', __name__)
ERROR_JSON = {"error": "Invalid request."}
WARNING_JSON = {"error": "Invalid request."}

class AttributeDict:
    def __init__(self, **kwargs):
        for key, value in kwargs.items():
            if isinstance(value, dict):
                self.__dict__[key] = AttributeDict(**value)
            else:
                self.__dict__[key] = value
    def __getattr__(self, key):
        # First, try to return from _response
        try:
            return self.__dict__['_response'][key]
        except KeyError:
            pass
        except AttributeError:
            pass

@policy_api.route('/register2', methods=['POST'])
def register2():
    """Register thing description at the target location. 
    If the current directory is the target location specified by `location` argument, the operation is processed locally
    
    Args:
        All of the following arguments are required and passed in the request URL.
        td (JSON str): the information of the thing description to be registered in JSON format
    Returns:
        HTTP Response: if the register is completed, a simple success string with HTTP status code 200 is returned
            Otherwise a reason is returned in the response and HTTP status code is set to 400
    """
    if not is_json_request(request, ["td"]):
        return jsonify(ERROR_JSON), 400
    
    body = request.get_json()
    thing_description = body["td"]
    mongo_service = MongoService()
    mongo_service.create_thing(thing_description)
    
    return make_response("Created", 200)

@policy_api.route('/policylist', methods=['POST'])
def policylist():
    if not is_json_request(request, ["td"]):
        return jsonify(ERROR_JSON), 400

    mongo_service = MongoService()
    mongo_service.find_policies()
    return make_response("Worked", 200)

@policy_api.route('/thinglist', methods=['POST'])
def thinglist():
    if not is_json_request(request, ["td"]):
        return jsonify(ERROR_JSON), 400

    mongo_service = MongoService()
    mongo_service.find_things()
    return make_response("Worked", 200)

@policy_api.route('/addPolicy', methods=['POST'])
def addPolicy():

    mongo_service = MongoService()
    mongo_service.add_policy()
    return make_response("Worked", 200)

@policy_api.route('/changePolicy', methods=['POST'])
def changePolicy():
    return

@policy_api.route('/deletePolicy', methods=['POST', 'DELETE'])
@policy_api.route('/deletePolicy/<policyid>', methods=['POST', 'DELETE'])
def deletePolicy(policyid):

    mongo_service = MongoService()
    mongo_service.delete_policy(policyid)
    return make_response(("Worked", 200))


@policy_api.route('/deleteDevice', methods=['POST', 'DELETE'])
@policy_api.route('/deleteDevice/<thing_id>', methods=['POST', 'DELETE'])
def deleteDevice(thing_id):
    mongo_service = MongoService()
    mongo_service.delete_thing(thing_id)
    return

@policy_api.route('/addDevice', methods=['POST'])
def addDevice():
    if not is_json_request(request, ["td"]):
        return jsonify(ERROR_JSON), 400

    body = request.get_json()
    thing_description = body["td"]
    mongo_service = MongoService()
    mongo_service.create_thing(thing_description)

    return make_response("Created", 200)

@policy_api.route('/notifications')
def notifications():
    mongo_service= MongoService(None)
    mongo_service.get_notifications()
    return

@policy_api.route('/delete2', methods=['POST', 'DELETE'])
@policy_api.route('/delete2/<thing_id>', methods=['POST', 'DELETE'])
def delete2(thing_id):
    """
        Deletes a thing
    """
    mongo_service = MongoService()
    mongo_service.delete_thing(thing_id)
    return make_response("Deleted", 200)

@policy_api.route('/policy', methods=['POST'])
def policy():
    if not is_json_request(request, ["td"]):
        return jsonify(ERROR_JSON), 400
    
    body = request.get_json()
    policy = body["td"]
    mongo_service = MongoService()
    mongo_service.create_policy(policy)
    
    return make_response("Created", 200)

@policy_api.route('/command', methods=['POST'])
def command():
    if not is_json_request(request, ["td"]):
        return jsonify(ERROR_JSON), 400
    
    body = request.get_json()
    command = body["td"]
    mongo_service = MongoService()
    criteria = dict()
    criteria["$or"] = [{"device_actor.type":"*"}, {"device_actor.type":command["device_actor"]["type"]}]
    criteria["action"] = command["action"]
    policies = mongo_service.find_policies(criteria)
    for policy in policies:
        actor_criteria = dict()
        actee_criteria = dict()
        actor_criteria["id"] = command["device_actor"]["id"]
        actee_criteria["@type"] = policy["device_actee"]["type"]
        actors = transform_links(mongo_service.find_things(actor_criteria))
        actees = transform_links(mongo_service.find_things(actee_criteria))
        things = transform_links(mongo_service.find_things(None))
        devices = [AttributeDict(**device) for device in things]
        for actor in actors:
            for actee in actees:
                device_actor = AttributeDict(**actor)
                device_actee = AttributeDict(**actee)
                if eval(policy["relation"]):
                    if eval(policy["assertion"], locals()):
                        error = ERROR_JSON
                        error["error"] = policy["response"]
                        error["message"] = policy["alert"]
                        return jsonify(error), 400
    return make_response("Success", 200)

app/templates/community.html
{% extends "home.html" %}


{% block dashboard_content %}
<style>
table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {background-color: #f2f2f2;}

th {
  background-color: #4CAF50;
  color: white;
}
.container {
    display: flex;
  }

  .policy-link {
    color: blue;
    text-decoration: underline;
    cursor: pointer;
}

#policy-details {
    border-radius: 10px;
}

#policy-details button {
    border-radius: 10px;
    padding: 1px 5px;
    margin-right: 10px;
}
</style>

    <div class="col-md-9">

<div style="text-align: right;">
  <img src = "static\images\Community.png" alt = "" width = "120" height ="120" style="position: absolute; top: -15px; right: -100px;">
</div>

<h2 class="text-center">Community Policies</h2>
      <h6 class="text-center">-Here you can download policies from other users-</h6>
      <p class="text-center">-If you download a policy, it will appear in the pending policies-</p>
      <p class="text-center">-If you delete a policy, it will be removed of the global database-</p>
      <br><br>

<div class="container">
  <div class="form-group">
    <label for="deviceType"><b>Device Type:</b></label>
    <select id="deviceType" name="deviceType">
      <option value="">--Please choose an option--</option>
      <option value="carbon_monoxide_detector">Carbon Monoxide Detector</option>
      <option value="smartphone">Smartphone</option>
      <option value="thermostat">Thermostat</option>
      <option value="washer">Washer</option>
      <option value="washing_machine">Washing Machine</option>
      <option value="weather_station">Weather Station</option>
      <option value="window">Window</option>
    </select>
  </div>
  <div class="form-group" style="margin-left: 250px">
    <label><b>Policies:</b></label>
    <div id="policy-list"></div>
  </div>
</div>

<script>
document.getElementById("deviceType").addEventListener("change", function() {
  var policyList = document.getElementById("policy-list");
  policyList.innerHTML = "";

  if (this.value !== "") {
    fetch(`http://localhost:8080/get_policies/community/${this.value}`)
      .then(response => response.json())
      .then(data => {
        data.forEach(policy => {
          var policyElement = document.createElement("div");
          policyElement.textContent = policy.policy_name;
          policyElement.classList.add("policy-link");
          policyList.appendChild(policyElement);
        });
      });
  }
});

</script>


<div id="policy-details" style="min-width: 600px; display: none; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); background-color: white; padding: 20px; border: 1px solid black;">
  <pre id="policy-code"></pre>
  <button id="close-popup">Close</button>
  <button id="delete-policy" style="position: absolute; right: 20px; background-color: red;">Delete Policy</button>
  <button id="download-policy" style="background-color: lightblue;">Download Policy</button>
</div>
<div id="deleteSuccessMessage" style="display: none; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); background-color: white; padding: 20px; border: 3px solid blue;">
    <p>Policy object deleted successfully!</p>
</div>
<div id="downloadSuccessMessage" style="display: none; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); background-color: white; padding: 20px; border: 3px solid blue;">
  <p>Policy object downloaded successfully!</p>
</div>
<div id="downloadFailMessage" style="display: none; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); background-color: white; padding: 20px; border: 3px solid red;">
  <p>Policy object downloaded failed!</p>
</div>
<script>
  var policyList = document.getElementById("policy-list");
policyList.addEventListener("click", function(event) {
  if (event.target.tagName === "DIV") {
    var deviceType = document.getElementById("deviceType").value;
    var policyName = event.target.textContent;

    fetch(`http://localhost:8080/policy_details/community/${deviceType}/${policyName}`)
      .then(response => response.text())
      .then(policyCode => {
        var policyCodeElement = document.getElementById("policy-code");
        policyCodeElement.textContent = policyCode;
        policyCodeElement.setAttribute("data-policy-name", policyName);

        var policyDetails = document.getElementById("policy-details");
        policyDetails.style.display = "block";
      });
  }
});
 var closePopupButton = document.getElementById("close-popup");
  closePopupButton.addEventListener("click", function() {
    var policyDetails = document.getElementById("policy-details");
    policyDetails.style.display = "none";
  });

var downloadPolicyButton = document.getElementById("download-policy");
downloadPolicyButton.addEventListener("click", function() {
    var deviceType = document.getElementById("deviceType").value;
    var policyNameElement = document.getElementById("policy-code");
    var policyName = policyNameElement.getAttribute("data-policy-name");
    fetch(`http://localhost:8080/add_policy_from_db/community/${deviceType}/${policyName}`, { method: 'POST' })
        .then(response => response.text())
        .then(result => {
            if (result === "Policy already exists") {
                var downloadFailMessage = document.getElementById("downloadFailMessage");
                downloadFailMessage.style.display = "block";
                setTimeout(function() {
                    downloadFailMessage.style.display = "none";
                }, 3000);
            } else {
                var downloadSuccessMessage = document.getElementById("downloadSuccessMessage");
                downloadSuccessMessage.style.display = "block";
                setTimeout(function() {
                    downloadSuccessMessage.style.display = "none";
                }, 3000);
                setTimeout(function() {
                    location.reload();
                }, 4000);
            }
        })
        .catch(error => {
            console.error(error);
        });
});


var deletePolicyButton = document.getElementById("delete-policy");
deletePolicyButton.addEventListener("click", function() {
    if (confirm("Are you sure you want to delete this policy?")) {
        var deviceType = document.getElementById("deviceType").value;
        var policyNameElement = document.getElementById("policy-code");
        var policyName = policyNameElement.getAttribute("data-policy-name");

        fetch(`http://localhost:8080/delete_policy/community/${deviceType}/${policyName}`, { method: 'DELETE' })
            .then(response => {
                if (!response.ok) {
                    throw new Error(`An error occurred: ${response.status}`);
                }
                return response.text();
            })
            .then(result => {
                console.log(result);

                var policyDetails = document.getElementById("policy-details");
                policyDetails.style.display = "none";
                var deleteSuccessMessage = document.getElementById("deleteSuccessMessage");
                deleteSuccessMessage.style.display = "block";
                setTimeout(function() {
                    deleteSuccessMessage.style.display = "none";
                }, 3000);
                setTimeout(function() {
                    location.reload();
                }, 4000);
            })
            .catch(error => {
                console.error(error);
            });
    }
});


</script>

<script>var deletePolicyButton = document.getElementById("delete-policy");
deletePolicyButton.addEventListener("click", function() {

});</script>
<script>
var deletePolicyButton = document.getElementById("delete-policy");
deletePolicyButton.addEventListener("click", function() {
  var deviceType = document.getElementById("deviceType").value;
  var policyNameElement = document.getElementById("policy-code");
  var policyName = policyNameElement.textContent;

  var policyNameMatch = policyName.match(/def\s+(\w+)\(/);
  if (policyNameMatch) {
    policyName = policyNameMatch[1];
  }

  fetch(`http://localhost:8080/delete_policy/community/${deviceType}/${policyName}`, { method: 'DELETE' })
    .then(response => {
      if (!response.ok) {
        throw new Error(`An error occurred: ${response.status}`);
      }
      return response.text();
    })
    .then(result => {

      var policyDetails = document.getElementById("policy-details");
      policyDetails.style.display = "none";
      location.reload();
    })
    .catch(error => {
      console.error(error);
    });
});
</script>


{% endblock dashboard_content %}
    </div>

app/templates/deletePolicy.html
{% extends "home.html" %}

{% block link %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static', filename='css/register.css')}}">
{% endblock link %}

{% block dashboard_content %}

      <h2 class="mb-5">Delete a Policy</h2>

        <div class="container-sm dashboard">
    <div class="row">
        <div class="col">
            <div class="row sidebar-row">

                <form class="delete-form" method="POST" action="{{url_for('policy_api.deletePolicy')}}">
                    <div>
                        <div class="form-group">
                            <table>
                                <tr>
                                    <th>ID</th>
                                </tr>
                                {% for policyid in policyid %}
                                    <tr>
                                        <td><li><input type="radio" name="policyid" value="{{policyid}}">{{ policyid }}</li></td>
                                    </tr>
                                {% endfor %}
                            </table>
                                    <div class="form-group">
          <button id="delete" type="button" class="btn btn-primary mt-3" onclick="submitForm()">Delete Policy</button>
        </div>
                            <script>
function submitForm() {
    let form = document.querySelector('.delete-form');
    let policyid = document.querySelector('input[name="policyid"]:checked').value;
    form.action = "{{url_for('policy_api.deletePolicy')}}".replace('deletePolicy', 'deletePolicy/' + policyid);
    form.submit();
}
</script>
                        </div>
                    </div>
                </form>
</div>
                </div>
</div>
        </div>
                </div>

    </div>
  </div>
</div>




{% endblock dashboard_content %}

app/templates/home.html
{% extends "layout.html" %}

{% block link %}

{% endblock link %}

{% block body %}
    <div class="col-md-9 main mx-auto">
      {% block dashboard_content%}
      {% endblock %}
    </div>


{% endblock body %}

{% block script %}
{{ super() }}

{% endblock script%}

app/templates/homescreen.html
{% extends "home.html" %}

{% block dashboard_content %}
<style>
    .center{
    display: block;
    margin-left: auto;
    margin-right: auto;
    }
</style>
<h2 class="mb-5 text-center">Welcome Admin!</h2>
<p class="text-center">This is your tool for <b>managing your policies</b> for IoT-Devices in your Smart Home or Smart Building!</p>
<p class="text-center">You have many different possibilites on how to interact with your policies.</p>
<br>
<p class="text-center">You can look at all available policies in your building under the <b>Policies</b>-tab and share or delete them.</p>
<p class="text-center">Under <b>New Policies</b> you can create your own policies.</p>
<br>
<p class="text-center">The <b>Notifications</b>-tab shows all notifications that occur in your system. <b>Pending Policies</b> shows the policies you created, where you can decide if you want to add it to your system.</p>
<br>
<p class="text-center">Finally in the <b>Community</b>-tab, you can download and add policies from other users to your system.</p>
<br>
<img src = "static\images\SmartHome.jpg" alt = "" width = "320" height = "200" class="center">
{% endblock dashboard_content %}

app/templates/layout.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}">
    {% block link %}

    {% endblock%}

    <style>
    .navbar .nav-item a {
      color: lightgray;
    }
     .nav-item img {
        margin-left: 20px;
    }
  </style>
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-secondary fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{{url_for('dashboard.home')}}">
                <h1>Administrative</h1>
                <h1>Interface</h1>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="nav-item">
                <a class="nav-link" href="{{url_for('dashboard.policylist')}}">Policies</a>
                <img src = "static\images\PoliciesPic.png" alt = "" width = "40" height ="40" style="margin-top: 20px;">
            </div>
            <div class="nav-item">
                <a class="nav-link" href="{{url_for('dashboard.addPolicy')}}">New Policy</a>
                    <img src = "static\images\NewPolicyPic.png" alt = "" width = "40" height ="40">
            </div>
            <div class="nav-item">
                <a class="nav-link" href="{{url_for('dashboard.notifications')}}">Notifications</a>
                    <img src = "static\images\NotificationsPic.png" alt = "" width = "40" height ="40" style="margin-top: 20px;">
            </div>
            <div class="nav-item">
                <a class="nav-link" href="{{url_for('dashboard.pendingPolicies')}}">Pending Policies</a>
                    <img src = "static\images\PendingPoliciesPic.png" alt = "" width = "40" height ="40">
            </div>
            <div class="nav-item">
                <a class="nav-link" href="{{url_for('dashboard.community')}}">Community Policies</a>
                    <img src = "static\images\Community.png" alt = "" width = "40" height ="40">
            </div>

        </div>
    </nav>

    <div class="body">

        {% block body %}

        {% endblock body%}
    </div>

    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

    {% block script %}
    {% endblock script %}
</body>

</html>

app/templates/notifications.html
{% extends "home.html" %}


{% block dashboard_content %}
<style>
  .center {
    display: flex;
    justify-content: center;
  }
  button {
  margin: 0 8px;
    border-radius: 9px;
  }
</style>

<div class="col-md-9">

<div style="text-align: right;">
  <img src = "static\images\NotificationsPic.png" alt = "" width = "100" height ="100" style="position: absolute; top: -15px; right: -20px;">
</div>

<h2 class="text-center">Notifications</h2>
    <h6 class="text-center">-Here you have an overview of all your notifications-</h6>
    <p class="text-center">-With the buttons down below, you can navigate through them-</p>
    <br><br>

<div id="notification-list"></div>
<div class="center">
  <button id="prev-page">Prev</button>
  <span id="page-numbers"></span>
  <button id="next-page">Next</button>
</div>

<script>
  var currentPage = 1;
  var perPage = 20;

  function getNotifications(page) {
    fetch(`http://localhost:8080/get_notifications?page=${page}`)
      .then(response => response.json())
      .then(data => {
        var notificationList = document.getElementById("notification-list");
        notificationList.innerHTML = '';

        data.forEach(notification => {
          var notificationElement = document.createElement("li");
          notificationElement.textContent = `${notification.message} (${notification.date} ${notification.time})`;
          notificationList.appendChild(notificationElement);
        });

        var pageNumbers = document.getElementById("page-numbers");
        pageNumbers.textContent = `Page ${currentPage}`;
      });
  }

  getNotifications(currentPage);

  document.getElementById('prev-page').addEventListener('click', function() {
    if (currentPage > 1) {
      currentPage--;
      getNotifications(currentPage);
    }
  });

  document.getElementById('next-page').addEventListener('click', function() {
    currentPage++;
    getNotifications(currentPage);
  });

function getNotifications(page) {
  fetch(`http://localhost:8080/get_notifications?page=${page}`)
    .then(response => response.json())
    .then(data => {
      var notificationList = document.getElementById("notification-list");
      notificationList.innerHTML = '';

      var table = document.createElement("table");
      table.style.borderCollapse = "collapse";
      table.style.width = "100%";

      var headerRow = document.createElement("tr");
      var messageHeader = document.createElement("th");
      messageHeader.textContent = "Message";
      headerRow.appendChild(messageHeader);
      var dateHeader = document.createElement("th");
      dateHeader.textContent = "Date";
      headerRow.appendChild(dateHeader);
      var timeHeader = document.createElement("th");
      timeHeader.textContent = "Time";
      headerRow.appendChild(timeHeader);
      table.appendChild(headerRow);

      data.forEach(notification => {
        var row = document.createElement("tr");
        var messageCell = document.createElement("td");
        messageCell.textContent = notification.message;
        row.appendChild(messageCell);
        var dateCell = document.createElement("td");
        dateCell.textContent = notification.date;
        row.appendChild(dateCell);
        var timeCell = document.createElement("td");
        timeCell.textContent = notification.time;
        row.appendChild(timeCell);
        table.appendChild(row);
      });

      notificationList.appendChild(table);

      var pageNumbers = document.getElementById("page-numbers");
      pageNumbers.textContent = `Page ${currentPage}`;
    });
}

</script>
{% endblock dashboard_content %}
</div>

app/templates/thinglist.html
{% extends "home.html" %}


{% block dashboard_content %}
<style>
table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {background-color: #f2f2f2;}

th {
  background-color: #4CAF50;
  color: white;
}
</style>

<div class="container-sm dashboard">
  <div class="row sidebar-row">
    <div class="col-md-3 menus list-group">
      <a class="list-group-item list-group-item-action {{ 'active' if tagname == 'thinglist' else '' }}"
        href="{{ url_for('dashboard.thinglist') }}">
        Thinglist
      </a>
      <a class="list-group-item list-group-item-action {{ 'active' if tagname == 'addDevice' else '' }}"
        href="{{ url_for('dashboard.addDevice') }}">
        Add Device
      </a>
      <a class="list-group-item list-group-item-action {{ 'active' if tagname == 'deleteDevice' else '' }}"
        href="{{ url_for('dashboard.deleteDevice') }}">
        Delete Device
      </a>
      <hr>
    </div>
    <div class="col-md-9">
<h2 class="mb-5">List of Things</h2>



<div class="container-sm dashboard">
    <div class="row">
        <div class="col">
            <div class="row sidebar-row">
                <div class="col-md-9 main">
                <form class="delete-form" method="POST" action="{{url_for('policy_api.thinglist')}}">
                    <div>
                        <div class="form-group">
                            <table>
                                <tr>
                                    <th>ID</th>
                                    <th>Title</th>
                                </tr>
                                {% for thing_id, thing_info in thing_ids.items() %}
                                    <tr>
                                        <td>{{ thing_id }}</td>
                                        <td>{{ thing_info["title"]}}</td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>

    </div>
  </div>
</div>
{% endblock dashboard_content %}